import type { ProjectState } from "./agent-types";

export const emptyProject: ProjectState = {
  runtimeVersion: "model-v1",
  conversationVersion: "per-problem-v1",
  id: "empty",
  name: "新作业",
  status: "CREATED",
  currentProblemId: null,
  teachingStage: "READING_PROBLEM",
  selectedMethod: "",
  progress: 0,
  responseMode: "deep",
  problems: [],
  materials: [],
  answerBlocks: [],
  teachingMessages: [],
  sideMessages: [],
  knowledgeCheckpoints: [],
  problemTeachingMessages: {},
  problemSideMessages: {},
  problemKnowledgeCheckpoints: {},
  problemTeachingStages: {},
  problemSelectedMethods: {},
  problemProgress: {},
  problemSolutionBlueprints: {},
  memories: [],
  checkpoints: [],
  rollbackPreview: null,
  answerVersion: 1,
  updatedAt: new Date(0).toISOString(),
};
